# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tests

on:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pipenv'

    - name: Set up environment
      run: |
        pip install pipenv
        pipenv install
        pipenv install smelly-python

    - name: Code smells
    - uses: smelly-python/smell-my-pr@main
      with: 
        github-token: ${{secrets.GITHUB_TOKEN}}
        command: pipenv run smelly-python -d src

    - name: Run unit tests
      run: |
        pipenv run pytest --cov=. --cov-config=./tests/config/.coveragerc ./tests/tests.py
